import { StarIcon } from "@heroicons/react/24/outline";


// const data = [
//     {
//         img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
//         title: "Nike Air Monarch IV",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "200",
//         company: "Nike",
//         color: "white",
//         category: "sneakers",
//         score: 5,

//     },
//     {
//         img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
//         title: "Nike Air Vapormax Plus",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "200",
//         company: "Nike",
//         color: "red",
//         score: 5,
//         category: "sneakers",
//         id
//     },

//     {
//         img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
//         title: "Nike Waffle One Sneaker",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "200",
//         company: "Nike",
//         color: "green",
//         score: 1,
//         category: "sneakers",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
//         title: "Nike Running Shoe",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "200",
//         company: "Adidas",
//         color: "black",
//         score: 2.5,
//         category: "sneakers",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
//         title: "Flat Slip On Pumps",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "200",
//         company: "Vans",
//         color: "green",
//         score: 2,
//         category: "flats",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
//         title: "Knit Ballet Flat",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "50",
//         company: "Adidas",
//         color: "black",
//         score: 4,
//         category: "flats",
//     },

//     {
//         img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
//         title: "Loafer Flats",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "50",
//         company: "Vans",
//         color: "white",
//         score: 2,
//         category: "flats",
//     },

//     {
//         img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
//         title: "Nike Zoom Freak",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "200",
//         company: "Nike",
//         color: "green",
//         score: 5,
//         category: "sneakers",
//     },

//     {
//         img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
//         title: "Nike Men's Sneaker",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "200",
//         company: "Adidas",
//         color: "blue",
//         score: 5,
//         category: "sneakers",
//     },

//     {
//         img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
//         title: "PUMA BLACK-OCE",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "150",
//         company: "Puma",
//         color: "green",
//         score: 5,
//         category: "sneakers",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
//         title: "Pacer Future Sneaker",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "150",
//         company: "Puma",
//         color: "red",
//         score: 5,
//         category: "sneakers",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
//         title: "Unisex-Adult Super",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "150",
//         company: "Puma",
//         color: "black",
//         score: 5,
//         category: "sneakers",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
//         title: "Roma Basic Sneaker",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "150",
//         company: "Puma",
//         color: "white",
//         score: 5,
//         category: "sneakers",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
//         title: "Pacer Future Doubleknit",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "150",
//         company: "Puma",
//         color: "black",
//         score: 5,
//         category: "sneakers",
//     },

//     {
//         img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
//         title: "Fusion Evo Golf Shoe",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "100",
//         company: "Puma",
//         color: "green",
//         score: 5,
//         category: "sneakers",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
//         title: "Rainbow Chex Skate",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "100",
//         company: "Vans",
//         color: "red",
//         score: 3,
//         score: 3,
//         category: "flats",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
//         title: "Low-Top Trainers",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "100",
//         company: "Vans",
//         color: "white",
//         score: 5,
//         score: 3,
//         category: "sandals",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
//         title: "Vans Unisex Low-Top",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "100",
//         company: "Vans",
//         color: "blue",
//         score: 3,
//         category: "sandals",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
//         title: "Classic Bandana Sneakers",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "50",
//         company: "Nike",
//         color: "black",
//         score: 3,
//         category: "sandals",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
//         title: "Chunky High Heel",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "50",
//         company: "Vans",
//         color: "black",
//         score: 3,
//         category: "heels",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
//         title: "Slip On Stiletto High Heel",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "100",
//         company: "puma",
//         color: "black",
//         score: 3,
//         category: "heels",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
//         title: "DREAM PAIRS Court Shoes",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "150",
//         company: "Nike",
//         color: "red",
//         score: 3,
//         category: "heels",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
//         title: "Nike Air Vapormax Plus",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "200",
//         company: "Nike",
//         color: "red",
//         score: 3,
//         category: "sneakers",
//     },

//     {
//         img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
//         title: "Low Mid Block Heels",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "200",
//         company: "Nike",
//         color: "black",
//         score: 3,
//         category: "heels",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
//         title: "Chunky High Heel",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "50",
//         company: "Adidas",
//         color: "black",
//         score: 3,
//         category: "heels",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
//         title: "Amore Fashion Stilettos",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "150",
//         company: "Adidas",
//         color: "white",
//         score: 3,
//         category: "heels",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
//         title: "Bridal Sandals Glitter",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "50",
//         company: "Adidas",
//         color: "black",
//         score: 3,
//         category: "heels",
//     },
//     {
//         img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
//         title: "Wedding Prom Bridal",
//         star: <StarIcon className="w-6 h-6" />,
//         reviews: "(123 بازدید)",
//         prevPrice: " تومان140,00",
//         newPrice: "50",
//         company: "Adidas",
//         color: "black",
//         score: 3,
//         category: "flats",
//     },
// ];
const data = [
    {
        "id": 1,
        "img": "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        "title": "Nike Air Monarch IV",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "white",
        "category": "sneakers",
        "score": 5
    },
    {
        "id": 2,
        "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
        "title": "Nike Air Vapormax Plus",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "red",
        "score": 5,
        "category": "sneakers"
    },
    {
        "id": 3,
        "img": "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
        "title": "Nike Waffle One Sneaker",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "green",
        "score": 1,
        "category": "sneakers"
    },
    {
        "id": 4,
        "img": "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
        "title": "Nike Running Shoe",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "200",
        "company": "Adidas",
        "color": "black",
        "score": 2.5,
        "category": "sneakers"
    },
    {
        "id": 5,
        "img": "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
        "title": "Flat Slip On Pumps",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "200",
        "company": "Vans",
        "color": "green",
        "score": 2,
        "category": "flats"
    },
    {
        "id": 6,
        "img": "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
        "title": "Knit Ballet Flat",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "50",
        "company": "Adidas",
        "color": "black",
        "score": 4,
        "category": "flats"
    },
    {
        "id": 7,
        "img": "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
        "title": "Loafer Flats",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "50",
        "company": "Vans",
        "color": "white",
        "score": 2,
        "category": "flats"
    },
    {
        "id": 8,
        "img": "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
        "title": "Nike Zoom Freak",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "green",
        "score": 5,
        "category": "sneakers"
    },
    {
        "id": 9,
        "img": "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
        "title": "Nike Men's Sneaker",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "200",
        "company": "Adidas",
        "color": "blue",
        "score": 5,
        "category": "sneakers"
    },
    {
        "id": 10,
        "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        "title": "PUMA BLACK-OCE",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "150",
        "company": "Puma",
        "color": "green",
        "score": 5,
        "category": "sneakers"
    },
    {
        "id": 11,
        "img": "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
        "title": "Pacer Future Sneaker",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "150",
        "company": "Puma",
        "color": "red",
        "score": 5,
        "category": "sneakers"
    },
    {
        "id": 12,
        "img": "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
        "title": "Unisex-Adult Super",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "150",
        "company": "Puma",
        "color": "black",
        "score": 5,
        "category": "sneakers"
    },
    {
        "id": 13,
        "img": "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
        "title": "Roma Basic Sneaker",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "150",
        "company": "Puma",
        "color": "white",
        "score": 5,
        "category": "sneakers"
    },
    {
        "id": 14,
        "img": "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
        "title": "Pacer Future Doubleknit",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "150",
        "company": "Puma",
        "color": "black",
        "score": 5,
        "category": "sneakers"
    },
    {
        "id": 15,
        "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        "title": "Fusion Evo Golf Shoe",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "100",
        "company": "Puma",
        "color": "green",
        "score": 5,
        "category": "sneakers"
    },
    {
        "id": 16,
        "img": "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
        "title": "Rainbow Chex Skate",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "100",
        "company": "Vans",
        "color": "red",
        "score": 3,
        "category": "flats"
    },
    {
        "id": 17,
        "img": "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
        "title": "Low-Top Trainers",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "100",
        "company": "Vans",
        "color": "white",
        "score": 5,
        "category": "sandals"
    },
    {
        "id": 18,
        "img": "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
        "title": "Vans Unisex Low-Top",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "100",
        "company": "Vans",
        "color": "blue",
        "score": 3,
        "category": "sandals"
    },
    {
        "id": 19,
        "img": "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
        "title": "Classic Bandana Sneakers",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "50",
        "company": "Nike",
        "color": "black",
        "score": 3,
        "category": "sandals"
    },
    {
        "id": 20,
        "img": "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
        "title": "Chunky High Heel",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "50",
        "company": "Vans",
        "color": "black",
        "score": 3,
        "category": "heels"
    },
    {
        "id": 21,
        "img": "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
        "title": "Slip On Stiletto High Heel",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "100",
        "company": "puma",
        "color": "black",
        "score": 3,
        "category": "heels"
    },
    {
        "id": 22,
        "img": "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
        "title": "DREAM PAIRS Court Shoes",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "150",
        "company": "Nike",
        "color": "red",
        "score": 3,
        "category": "heels"
    },
    {
        "id": 23,
        "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
        "title": "Nike Air Vapormax Plus",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "red",
        "score": 3,
        "category": "sneakers"
    },
    {
        "id": 24,
        "img": "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
        "title": "Low Mid Block Heels",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "200",
        "company": "Nike",
        "color": "black",
        "score": 3,
        "category": "heels"
    },
    {
        "id": 25,
        "img": "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
        "title": "Chunky High Heel",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "50",
        "company": "Adidas",
        "color": "black",
        "score": 3,
        "category": "heels"
    },
    {
        "id": 26,
        "img": "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
        "title": "Amore Fashion Stilettos",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "150",
        "company": "Adidas",
        "color": "white",
        "score": 3,
        "category": "heels"
    },
    {
        "id": 27,
        "img": "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
        "title": "Bridal Sandals Glitter",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "50",
        "company": "Adidas",
        "color": "black",
        "score": 3,
        "category": "heels"
    },
    {
        "id": 28,
        "img": "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
        "title": "Wedding Prom Bridal",
        "star": "<StarIcon className=\"w-6 h-6\" />",
        "reviews": "(123 بازدید)",
        "prevPrice": " تومان140,00",
        "newPrice": "50",
        "company": "Adidas",
        "color": "black",
        "score": 3,
        "category": "flats"
    }
]


export default data;
export const socials = [
    {
        name: 'twitter',
        url: '/twitter.svg',
    },
    {
        name: 'linkedin',
        url: '/linkedin.svg',
    },
    {
        name: 'instagram',
        url: '/instagram.svg',
    },
    {
        name: 'facebook',
        url: '/facebook.svg',
    },
];